name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller --onefile main.py
    - name: Upload Build Results
      uses: actions/upload-artifact@v2.2.3
      with:
        name: linux_build
        path: dist/
  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller --onefile main.py
    - name: Upload Build Results
      uses: actions/upload-artifact@v2.2.3
      with:
        name: macos_build
        path: dist/
  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller --onefile main.py
    - name: Upload Build Results
      uses: actions/upload-artifact@v2.2.3
      with:
        name: windows_build
        path: dist/
